import 'dart:convert';
import 'dart:math';

import 'package:engaged/models.dart';
import 'package:engaged/search/search_models.dart';
import 'package:http/http.dart';
import 'package:http/http.dart ' as http;

// Future<List<PostModel>> getPosts() async {
//   var uri = Uri.parse("https://dummyjson.com/posts");

//   var response = await apicall.get(uri);
//   List<PostModel> posts = [];
//   if (response.statusCode == 200) {
//     var jsonData = jsonDecode(response.body);
//     var jsonDataList = jsonData['posts'] as Iterable;
//     for (var i in jsonDataList) {
//       posts.add(PostModel.fromJson(i));
//     }
//   }
//   return posts;
// }

// List<Myapi> Myapilist = [];
// Future<List<Myapi>> getApi() async {
//   final response =
//       await http.get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
//   var data = jsonDecode(response.body.toString());
//   if (response.statusCode == 200) {
//     for (Map<String, dynamic> i in data) {
//       Myapilist.add(Myapi.fromJson((i)));
//     }
//     return Myapilist;
//   } else {
//     return Myapilist;
//   }
// }
List<SearchModel> search = [];
Future<List<SearchModel>> getAllProducts() async {
  var uri = Uri.parse('https://dummyjson.com/products');
  final response = await http.get(uri);
  var data = jsonDecode(response.body);
  print(response);
  if (response.statusCode == 200) {
    for (var i in data['products']) {
      search.add(SearchModel.fromJson(i));
    }
    return search;
  } else {
    return search;
  }
}

List<Autogenerated> searchResult = [];

Future<List<Autogenerated>> getSearchData(String searchText) async {
  var uri = Uri.parse('https://dummyjson.com/products/search?q=$searchText');
  final response = await http.get(uri);
  var data = jsonDecode(response.body);
  if (response.statusCode == 200) {
    for (var i in data['products']) {
      searchResult.add(Autogenerated.fromJson(i));
    }
    return searchResult;
  } else {
    return searchResult;
  }
}
